server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/hearbridge?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 26379
      database: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yezhen.hearbridge.backend.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.yezhen.hearbridge.backend.mapper: debug

hearbridge:
  auth:
    token-prefix: "hearbridge:app:login:"
    token-expire-days: 7
  minio:
    bucket: cwasa-static
    access-key: admin
    secret-key: admin123456

