# ============================================================
# HearBridge Backend 本地开发配置
# ============================================================

# ------------------------------------------------------------
# 服务端口配置
# ------------------------------------------------------------
server:
  port: 8080

# ------------------------------------------------------------
# Spring 基础配置
# ------------------------------------------------------------
spring:
  # MySQL 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/hearbridge?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置
  data:
    redis:
      host: 127.0.0.1
      port: 26379
      database: 1

  # 文件上传配置
  servlet:
    multipart:
      # 单个文件最大上传大小
      max-file-size: 10MB

      # 单次请求最大上传大小
      max-request-size: 20MB

# ------------------------------------------------------------
# MyBatis 配置
# ------------------------------------------------------------
mybatis:
  # Mapper XML 文件位置
  mapper-locations: classpath:mapper/*.xml

  # 实体类包路径
  type-aliases-package: com.yezhen.hearbridge.backend.entity

  configuration:
    # 开启下划线转驼峰映射
    # 例如：cover_object_key -> coverObjectKey
    map-underscore-to-camel-case: true

# ------------------------------------------------------------
# 日志配置
# ------------------------------------------------------------
logging:
  level:
    # 打印 Mapper SQL 调试日志
    com.yezhen.hearbridge.backend.mapper: debug

# ------------------------------------------------------------
# HearBridge 自定义配置
# ------------------------------------------------------------
hearbridge:
  auth:
    token-prefix: "hearbridge:app:login:"
    token-expire-days: 7

    # 管理端登录 token Redis 前缀。
    admin-token-prefix: "hearbridge:admin:login:"

    # 管理端登录 token 过期天数。
    admin-token-expire-days: 7

  minio:
    endpoint: http://127.0.0.1:9000
    bucket: cwasa-static
    access-key: admin
    secret-key: admin123456

  python:
    gesture-service-base-url: http://127.0.0.1:8000
