package com.yezhen.hearbridge.backend.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.yezhen.hearbridge.backend.config.DeepSeekProperties;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;

/**
 * DeepSeek OpenAI-compatible Chat Completions 客户端。
 */
@Service
public class DeepSeekSemanticClient {

    private static final String SYSTEM_PROMPT = """
            You are a sign-language gloss candidate ranker and faithful naturalization translator.

            You will receive:
            - rawSequence: the recognizer's original gloss output.
            - segments: ordered recognition segments with rawLabel and TopK visual evidence.
            - candidates: legal candidate gloss sequences generated by a program.

            Your tasks:
            1. Choose exactly one candidateId from the provided candidates.
            2. Return correctedGlossSequence exactly equal to the selected candidate sequence.
            3. Convert correctedGlossSequence into a faithful natural English sentence or fragment.
            4. Translate that meaning into faithful natural Chinese.

            Hard candidate constraints:
            - Do not create a new gloss sequence.
            - Do not add, remove, reorder, or replace gloss words outside the selected candidate.
            - selectedCandidateId must be one of the provided candidateIds.
            - correctedGlossSequence must exactly match the selected candidate sequence.
            - If your written correctedGlossSequence differs from the selected candidate, the program will ignore your written gloss and trust only selectedCandidateId.

            Candidate selection principle:
            - Choose the candidate that best represents a realistic short communication gloss and is supported by visual evidence.
            - If rawSequence is already coherent and realistic, choose the raw candidate.
            - If rawSequence has one clear inserted boundary/noise word and deleting it creates a clearer communication gloss, prefer that deletion candidate.
            - If rawSequence has the right length but one local word has an obviously wrong semantic role, consider a same-segment TopK replacement candidate.
            - If every edited candidate is weak, over-deleted, or semantically less faithful than raw, choose raw.

            Faithful naturalization rules:
            Allowed:
            - Add function words needed for English grammar: to, for, with, at, in, on, a, an, the, am, is, are, do, does, will, can.
            - Convert telegraphic gloss into natural word order when the relation is clear.
            - Use natural Chinese wording instead of word-by-word Chinese when the meaning is clear.

            Forbidden:
            - Do not add new story content that is not implied by the gloss.
            - Do not invent a subject such as I, my, we, our unless the gloss clearly implies it.
            - Do not invent intentions like available/free, need, can, because, should, or want unless the gloss contains corresponding evidence.
            - Do not turn an incomplete fragment into a fully specific sentence by guessing missing meaning.
            - Do not turn "today you" into "Are you available today?" because available/free is not in the gloss.
            - Do not turn "no learn school friend language" into "No, I learn language with a friend at school" unless the subject and relation are clear.
            - Do not over-polish wrong or incomplete glosses into confident fluent sentences.

            Incomplete or low-confidence gloss handling:
            - If the corrected gloss lacks a clear action, subject, object, or relation, set isIncomplete=true.
            - For incomplete glosses, englishSentence may be a fragment ending with "...".
            - For incomplete glosses, chineseTranslation may also be a fragment ending with "……".
            - Set translationConfidence to "high" only when the gloss relation is clear.
            - Set translationConfidence to "medium" when the gloss is understandable but somewhat telegraphic.
            - Set translationConfidence to "low" when the gloss is incomplete, odd, or only partially interpretable.

            Examples:
            - gloss: ["you", "go", "school"]
              englishSentence: "You go to school."
              chineseTranslation: "你去学校。"
              translationConfidence: "high"
              isIncomplete: false

            - gloss: ["please", "help", "teacher"]
              englishSentence: "Please help the teacher."
              chineseTranslation: "请帮助老师。"
              translationConfidence: "high"
              isIncomplete: false

            - gloss: ["today", "you"]
              englishSentence: "Today, you..."
              chineseTranslation: "今天，你……"
              translationConfidence: "low"
              isIncomplete: true

            - gloss: ["teacher", "language", "sorry"]
              englishSentence: "Teacher, language, sorry..."
              chineseTranslation: "老师，语言，对不起……"
              translationConfidence: "low"
              isIncomplete: true

            Return JSON only:
            {
              "selectedCandidateId": "C000",
              "correctedGlossSequence": ["word1", "word2"],
              "englishSentence": "A faithful English sentence or fragment.",
              "chineseTranslation": "忠实的中文句子或片段。",
              "translationConfidence": "high_or_medium_or_low",
              "isIncomplete": false,
              "translationNote": "brief note about any uncertainty or missing information",
              "reason": "brief reason for candidate choice"
            }
            """;

    private final DeepSeekProperties deepSeekProperties;

    private final ObjectMapper objectMapper;

    /**
     * JDK HttpClient，避免额外引入 WebFlux 或新的 HTTP 依赖。
     */
    private final HttpClient httpClient;

    public DeepSeekSemanticClient(
            DeepSeekProperties deepSeekProperties,
            ObjectMapper objectMapper) {
        this.deepSeekProperties = deepSeekProperties;
        this.objectMapper = objectMapper;
        this.httpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(resolveTimeoutSeconds()))
                .build();
    }

    /**
     * 调用 DeepSeek 获取语义修正 JSON。
     *
     * @param request 原始识别结果
     * @return DeepSeek 返回内容解析出的 JSON 节点
     */
    public JsonNode correct(Object request) {
        if (!StringUtils.hasText(deepSeekProperties.getApiKey())) {
            throw new IllegalStateException("DeepSeek API Key 未配置");
        }

        try {
            String requestBody = objectMapper.writeValueAsString(buildRequestBody(request));

            HttpRequest httpRequest = HttpRequest.newBuilder()
                    .uri(URI.create(getNormalizedBaseUrl() + "/chat/completions"))
                    .timeout(Duration.ofSeconds(resolveTimeoutSeconds()))
                    .header("Content-Type", "application/json")
                    .header("Authorization", "Bearer " + deepSeekProperties.getApiKey().trim())
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody, StandardCharsets.UTF_8))
                    .build();

            HttpResponse<String> response = httpClient.send(
                    httpRequest,
                    HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8)
            );

            if (response.statusCode() < 200 || response.statusCode() >= 300) {
                throw new IllegalStateException(
                        "DeepSeek 调用失败，HTTP " + response.statusCode() + "：" + abbreviate(response.body())
                );
            }

            JsonNode responseJson = objectMapper.readTree(response.body());
            String content = responseJson
                    .path("choices")
                    .path(0)
                    .path("message")
                    .path("content")
                    .asText("");

            if (!StringUtils.hasText(content)) {
                throw new IllegalStateException("DeepSeek 返回内容为空");
            }

            return objectMapper.readTree(cleanJsonContent(content));
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("DeepSeek 调用被中断", exception);
        } catch (IOException exception) {
            throw new IllegalStateException("DeepSeek 调用或 JSON 解析失败", exception);
        }
    }

    private ObjectNode buildRequestBody(Object request) throws IOException {
        ObjectNode body = objectMapper.createObjectNode();

        body.put("model", StringUtils.hasText(deepSeekProperties.getModel())
                ? deepSeekProperties.getModel().trim()
                : "deepseek-v4-flash");
        body.put("temperature", 0);
        body.put("stream", false);
        body.putObject("thinking").put("type", "disabled");

        ArrayNode messages = body.putArray("messages");
        messages.addObject()
                .put("role", "system")
                .put("content", SYSTEM_PROMPT);
        messages.addObject()
                .put("role", "user")
                .put("content", "INPUT:\n" + objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(request));

        return body;
    }

    private String getNormalizedBaseUrl() {
        String baseUrl = deepSeekProperties.getBaseUrl();

        if (!StringUtils.hasText(baseUrl)) {
            throw new IllegalStateException("DeepSeek API 地址未配置");
        }

        String trimmed = baseUrl.trim();
        return trimmed.endsWith("/")
                ? trimmed.substring(0, trimmed.length() - 1)
                : trimmed;
    }

    private int resolveTimeoutSeconds() {
        Integer timeoutSeconds = deepSeekProperties.getTimeoutSeconds();
        if (timeoutSeconds == null || timeoutSeconds <= 0) {
            return 30;
        }
        return timeoutSeconds;
    }

    private String cleanJsonContent(String content) {
        String cleaned = content.trim();

        if (cleaned.startsWith("```")) {
            int firstLineEnd = cleaned.indexOf('\n');
            if (firstLineEnd >= 0) {
                cleaned = cleaned.substring(firstLineEnd + 1).trim();
            }
            if (cleaned.endsWith("```")) {
                cleaned = cleaned.substring(0, cleaned.length() - 3).trim();
            }
        }

        int jsonStart = cleaned.indexOf('{');
        int jsonEnd = cleaned.lastIndexOf('}');
        if (jsonStart >= 0 && jsonEnd > jsonStart) {
            cleaned = cleaned.substring(jsonStart, jsonEnd + 1).trim();
        }

        return cleaned;
    }

    private String abbreviate(String value) {
        if (value == null) {
            return "";
        }

        String normalized = value.replaceAll("\\s+", " ").trim();
        if (normalized.length() <= 500) {
            return normalized;
        }
        return normalized.substring(0, 500) + "...";
    }
}
